version: '3'
services:

  #Ubuntu

  #Database MySql
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: ESII2ndMilestone
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
    networks:
      - wpsite  

  #phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: PhpMyadmin
    restart: always
    ports:
      - '7000:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - wpsite

  #WordPress CMS
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    restart: always
    volumes: ['./wp-content:/var/www/html/wp-content'] 
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: ESII2ndMilestone
      WORDPRESS_CONFIG_EXTRA:
        define( 'FS_METHOD', 'direct' );
    ports:
      - 8000:80
    networks:
      - wpsite

networks:
  wpsite:
volumes:
  db_data: